import SwiftUI

// MARK: - Loading indicator

struct AnimatedDotsView: View {
    var color: Color = SayWellTheme.lagoon.opacity(0.85)
    var dotSize: CGFloat = 5

    var body: some View {
        TimelineView(.periodic(from: .now, by: 0.32)) { context in
            HStack(spacing: 4) {
                ForEach(0..<3, id: \.self) { index in
                    Circle()
                        .fill(color.opacity(opacity(for: index, at: context.date)))
                        .frame(width: dotSize, height: dotSize)
                }
            }
        }
        .accessibilityLabel("Loading")
    }

    private func opacity(for index: Int, at date: Date) -> Double {
        let phase = date.timeIntervalSinceReferenceDate / 0.32
        let wave = sin((phase + Double(index) * 0.34) * .pi * 2)
        return 0.32 + 0.68 * max(0, wave)
    }
}

// MARK: - Result area states

struct TranslationLoadingCard: View {
    let phrase: String

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack(spacing: 10) {
                AnimatedDotsView()
                Text(loadingMessage)
                    .font(.system(.subheadline, design: .rounded).weight(.semibold))
                    .foregroundStyle(SayWellTheme.lagoon.opacity(0.9))
            }

            if !phrase.isEmpty {
                Text("“\(phrase)”")
                    .font(.system(.title3, design: .serif))
                    .foregroundStyle(SayWellTheme.ink.opacity(0.62))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .lineLimit(3)
            }
        }
        .padding(18)
        .background(SayWellTheme.foam.opacity(0.92), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
        .overlay {
            RoundedRectangle(cornerRadius: 18, style: .continuous)
                .strokeBorder(SayWellTheme.brand.opacity(0.2), lineWidth: 1)
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Translating \(phrase)")
    }

    private var loadingMessage: String {
        let trimmed = phrase.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > 22 else { return "Finding the right English" }
        return "Translating your Singlish"
    }
}

struct TranslationWelcomeCard: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Label {
                Text("Your English will appear here")
                    .font(.system(.subheadline, design: .rounded).weight(.semibold))
                    .foregroundStyle(SayWellTheme.lagoon.opacity(0.85))
            } icon: {
                Image(systemName: "text.bubble")
                    .symbolRenderingMode(.hierarchical)
                    .foregroundStyle(SayWellTheme.brand)
            }

            VStack(alignment: .leading, spacing: 8) {
                tipRow("Type how you'd text a friend — roman letters, not Sinhala script")
                tipRow("Tap Translate or press return on the keyboard")
                tipRow("Try an example chip below to see it in action")
            }
        }
        .padding(18)
        .background(SayWellTheme.foam.opacity(0.65), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
        .overlay {
            RoundedRectangle(cornerRadius: 18, style: .continuous)
                .strokeBorder(SayWellTheme.lagoon.opacity(0.1), lineWidth: 1)
        }
    }

    private func tipRow(_ text: String) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: "sparkle")
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(SayWellTheme.brand.opacity(0.75))
                .padding(.top, 4)
            Text(text)
                .font(.system(.footnote, design: .rounded))
                .foregroundStyle(SayWellTheme.ink.opacity(0.68))
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}

struct TranslationSourceBadge: View {
    let source: TranslationSource

    var body: some View {
        Text(label)
            .font(.system(.caption2, design: .rounded).weight(.semibold))
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(tint.opacity(0.12), in: Capsule())
            .foregroundStyle(tint)
            .accessibilityLabel(accessibilityLabel)
    }

    private var label: String {
        switch source {
        case .builtin, .cache: "Instant"
        case .model: "AI"
        }
    }

    private var tint: Color {
        switch source {
        case .builtin, .cache: SayWellTheme.brand
        case .model: .orange
        }
    }

    private var accessibilityLabel: String {
        switch source {
        case .builtin: "Built-in phrase"
        case .cache: "Served from cache"
        case .model: "Generated by AI"
        }
    }
}
